seed: 42
evaluate: False

trainer_params:
  accelerator: null
  gpus: 1
  default_root_dir: /kaggle/project
  max_epochs: 100
  log_every_n_steps: 10
  gradient_clip_val: 0.1

logger:
  type: TensorBoardLogger
  save_dir: ./logs/
  name: left-right-broad-invpyramid-linear
  version: layer=1|lr=1.0e-4|

hparams:
  lr: 1.0e-4
  weight_decay: 1.0e-5
  optimizer: adam
  warmup_epochs: 1
  batch_size: 512
  k: 0
  per_k: 0
  num_classes: 20
  num_workers: 6

ckpt_callback:
  save_top_k: 2
  monitor: val_acc
  mode: max
  save_last: True