ckpt_callback:
  mode: max
  monitor: val_acc
  save_last: true
  save_top_k: 2
dataset:
  raw_data_dir: ../datasets/cifar-100-python/
  test_dir: datasets/CIFAR100/test/coarse
  train_dir: datasets/CIFAR100/train/coarse
  val_dir: datasets/CIFAR100/test/coarse
evaluate: true
exp_name: single_head
hparams:
  arch: vgg11
  batch_size: 256
  dropout: 0.6
  k: 0.0
  lr: 0.0001
  mode: coarse
  num_workers: 6
  per_k: 0.0
  weight_decay: 0.001
logger:
  type: TensorBoardLogger
save_dir: ./runs/
seeds:
- 0
trainer_params:
  accelerator: gpu
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 1
  default_root_dir: ./runs
  devices: auto
  log_every_n_steps: 50
  max_epochs: 150
