ckpt_callback:
  mode: max
  monitor: val_acc
  save_last: true
  save_top_k: 2
dataset:
  raw_data_dir: ../datasets/cifar-100-python/
  test_dir: datasets/CIFAR100/test/fine
  train_dir: datasets/CIFAR100/train/fine
  val_dir: datasets/CIFAR100/test/fine
evaluate: true
exp_name: single_head
hparams:
  arch: vgg11
  batch_size: 256
  dropout: 0.6
  k: 0.0
  lr: 0.0001
  mode: fine
  num_workers: 6
  per_k: 0.0
  weight_decay: 0.001
logger:
  type: TensorBoardLogger
save_dir: ./runs/
seeds:
- 0
- 1
- 2
- 3
- 4
trainer_params:
  accelerator: gpu
  default_root_dir: ./runs
  devices: auto
  gradient_clip_val: 10
  log_every_n_steps: 2
  max_epochs: 100
