seeds: [8]       # it is possible to do multiple seeds (if there is only 1, it must still be in an array)
evaluate: True
save_dir: ./runs/   # exp output folder: logs, checkpoints, hparams and accuracy
exp_name: single_head

trainer_params:
  accelerator: null
  gpus: 1
  default_root_dir: ./runs  # root folder for pytorch-lightning (but logs and checkpoints go to the logger save_dir)
  max_epochs: 30
  log_every_n_steps: 2
  gradient_clip_val: 10

dataset:
  train_dir: ../datasets/CIFAR100/train/coarse
  val_dir: ../datasets/CIFAR100/test/coarse
  test_dir: ../datasets/CIFAR100/test/coarse

logger:
  type: TensorBoardLogger

hparams:
  arch: 'resnet9'
  mode: 'coarse'              # the one head configuration:    [fine | coarse | feature]
  lr: 1.0e-4
  weight_decay: 1.0e-3
  batch_size: 256
  k: 0.0
  per_k: 0.0
  num_workers: 6
  # model_path: path_to_checkpoint  # source location of specific checkpoint to load

ckpt_callback:
  save_top_k: 2
  monitor: val_acc
  mode: max
  save_last: True



# **** classification
# unilateral, 1 head
#     train/test hem + head together (1), load whole architecture chkpnts (0)
#
# **** hemispheres
# unilateral, 2 heads
#     train/test hem(s) + head(s) together (1), load whole architecture chkpnts (0)
#
# bilateral, 2 heads
#     train/test hem(s) + head(s) together (1), load whole architecture chkpnts (0), load hemisphere chkpnts (1)
#
