seed: 42
evaluate: False

trainer_params:
  accelerator: null
  gpus: 1
  default_root_dir: /root_dir   # destination of logs and checkpoints
  max_epochs: 100
  log_every_n_steps: 10
  gradient_clip_val: 10

logger:
  type: TensorBoardLogger
  save_dir: ./logs/
  name: narrow-pyramid-sparsity
  version: lr=0.0001|opt=adam|

hparams:
  lr: 1.0e-4
  weight_decay: 1.0e-3
  optimizer: adam
  warmup_epochs: 1
  batch_size: 256
  k: 0.9
  per_k: 0.9
  num_classes: 100
  num_workers: 6
  model_path: /path/to/model_checkpoint  # source location of checkpoints

ckpt_callback:
  save_top_k: 2
  monitor: val_acc
  mode: max
  save_last: True