ckpt_callback:
  mode: max
  monitor: val_acc
  save_last: true
  save_top_k: 2
dataset:
  test_dir: ../datasets/CIFAR100/test/fine
  train_dir: ../datasets/CIFAR100/train/fine
  val_dir: ../datasets/CIFAR100/test/fine
evaluate: false
hparams:
  batch_size: 256
  k: 0.9
  lr: 0.0001
  num_classes: 100
  num_workers: 6
  optimizer: adam
  per_k: 0.9
  warmup_epochs: 1
  weight_decay: 0.001
logger:
  name: fine
  save_dir: ./logs/
  type: TensorBoardLogger
  version: lr=0.0001|opt=adam|
seeds:
- 2
trainer_params:
  accelerator: null
  default_root_dir: runs
  gpus: 1
  gradient_clip_val: 1
  log_every_n_steps: 1
  max_epochs: 4
