seed: 42
evaluate: False

trainer_params:
  accelerator: null
  gpus: 1
  default_root_dir: /kaggle/project
  max_epochs: 60
  log_every_n_steps: 10

logger:
  type: TensorBoardLogger
  save_dir: ./logs/
  name: sparse-autoencoder-hpsearch
  version: res9|lr=1.0e-4|bs=64|k=3|%k=0.3|latent_dim=64|

hparams:
  lr: 1.0e-3
  weight_decay: 1.0e-5
  optimizer: adam
  warmup_epochs: 0
  batch_size: 256
  k: 3
  per_k: 0.3
  latent_dim: 128

ckpt_callback:
  save_top_k: 3
  monitor: val_loss
  mode: min
  save_last: True