seed: 42
evaluate: False

trainer_params:
  accelerator: null
  gpus: 1
  default_root_dir: /kaggle/project
  max_epochs: 100
  log_every_n_steps: 10

logger:
  type: TensorBoardLogger
  save_dir: ./logs/
  name: unsupervised-feature-pyramid
  version: lr

hparams:
  lr: 1.0e-4
  weight_decay: 1.0e-5
  optimizer: adam
  warmup_epochs: 0
  batch_size: 128
  latent_dim: 64

ckpt_callback:
  save_top_k: 3
  monitor: val_loss
  mode: min
  save_last: True